name: Compile AHK to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile AutoHotkey Script
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up AutoHotkey
      run: |
        choco install autohotkey

    - name: Compile AHK Script to Executable
      run: cmd /c '"C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe" /in Jiggler.ahk /out Jiggler.exe'

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Jiggler-Executable
        path: Jiggler.exe
